version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: social
      POSTGRES_USER: quarkus
      POSTGRES_PASSWORD: quarkus
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
